<center> 

# DSSI: Summer 2024
## DataFrames

#### Authored by: Susanna Lange, PhD

<center>
<img src="https://raw.githubusercontent.com/amandakube/Data118LectureImages/main/UChicago_DSI.png" alt="UC-DSI" width="300" height="100">
</center>

In [1]:
# This line imports the Numpy module
import numpy as np

## Grouping or Storing Data

Recall...

- Lists, Tuples, Sets, Dictionaries (built-in to Python)

- Arrays (found in the NumPy library)

- DataFrames (in Pandas)

## Grouping Data with DataFrames (from the Pandas library)

- Gives rows and columns of data
- Rows are "individuals" or "instances"
- Columns are attributes of those individuals

#### DataFrames


- A DataFrame has an **index** that refers to the rows and **column names** referring to the columns

<center>
<img src="
https://raw.githubusercontent.com/SusannaLange/Data_118_images/main/DSSI_images/DataFrames/chicago_dataframe.png" alt="DataFrame_chicagoairbnb" width="800">
</center>

## How can we make a DataFrame?

```python
import pandas as pd #import a new library or module
```

From this library, we want to extract the 'DataFrame' function

```python
pd.DataFrame()
```

In [ ]:
small_chicago = pd.DataFrame(
    { 1:[2384,4505,7126],  #ID
      2:['Hyde Park','South Lawndale','West Town'], #neighbourhood
     3:[60,105,60], #price
    4:['private room', 'entire home', 'entire home']}) #room_type

small_chicago

      1               2    3             4
0  2384       Hyde Park   60  private room
1  4505  South Lawndale  105   entire home
2  7126       West Town   60   entire home

Above: DataFrame using a Dictionary

   -  Creates a DataFrame along a column-axis
    
   - keys of dictionary become the column titles

**Aside**: But how does this differ from 2-dimensional np.array?! Or a higher dimensional list?

In [ ]:
#This is a 2D array
my_array = np.array([[2384,4505,7126],  #ID
      ['Hyde Park','South Lawndale','West Town'], #neighbourhood
     [60,105,60], #price
    ['private room', 'entire home', 'entire home']])
print(my_array)

[['2384' '4505' '7126']
 ['Hyde Park' 'South Lawndale' 'West Town']
 ['60' '105' '60']
 ['private room' 'entire home' 'entire home']]

### We can specify the column names and indices

In [ ]:
small_chicago = pd.DataFrame(
    { 'id':[2384,4505,7126],  #ID
      'neighbourhood':['Hyde Park','South Lawndale','West Town'], #neighbourhood
     'price':[60,105,60], #price
    'room type':['private room', 'entire home', 'entire home']}, index=['a','b','c']) #room_type

small_chicago

     id   neighbourhood  price     room type
a  2384       Hyde Park     60  private room
b  4505  South Lawndale    105   entire home
c  7126       West Town     60   entire home

### Define by rows instead of by columns

In [ ]:
# created from lists.
# You specify rows here!
small_chicago = pd.DataFrame(
    [[2384,'Hyde Park', 60, 'private room'],
      [4505,'South Lawndale',105,'entire home'],
     [7126,'West Town',60, 'entire home']], index=['a','b','c'],
    columns = ['id', 'neighbourhood', 'price', 'room type']) #room_type

small_chicago

     id   neighbourhood  price     room type
a  2384       Hyde Park     60  private room
b  4505  South Lawndale    105   entire home
c  7126       West Town     60   entire home

## DataFrames are built from *series*

In [ ]:
small_chicago

     id   neighbourhood  price     room type
a  2384       Hyde Park     60  private room
b  4505  South Lawndale    105   entire home
c  7126       West Town     60   entire home

So...

 - Python has lists
 - Numpy has arrays
 - and Pandas has series as the *basic* way to store data

 What is a series?

### Pandas series
#### Pandas defines a basic collection data type called a "series" that is analogous to a one dimentional array in numpy.

In [ ]:
Neighborhoods= pd.Series(['Hyde Park','South Lawndale','West Town'])
print(Neighborhoods)

0         Hyde Park
1    South Lawndale
2         West Town
dtype: object

## We can use series to make DataFrames

In fact, a dataframe is a sequence of aligned series objects
- “aligned” means that they share the same index

#### Series are a bit more flexible than arrays.  For example you can specify your own index for a series, and the indexes don't have to be integers.

In [ ]:
my_Neighborhoods= pd.Series(['Hyde Park','South Lawndale','West Town'], index = ['a', 'b', 'c'])
print(my_Neighborhoods)

a         Hyde Park
b    South Lawndale
c         West Town
dtype: object

### We can extract elements from a series!

In [ ]:
my_Neighborhoods[1]

'South Lawndale'

In [ ]:
my_Neighborhoods['b']

'South Lawndale'

    
np.array:
 - supports integer-based indexing
    
Series:
 - supports both integer- and label-based indexing
 - performs operations involving the index or location
    
    
“Indexing” is refering to an element of an iterable (series, array, list, ...) by its position within the iterable. “Slicing” is refering to a subset of elements from something like an array, list, series, or dataframe based on their indices.

### One more way to create a DataFrame!

We can read in a file.

### Filepaths

 - directions to access files on our local machines.

 - Filepaths can include the names of files and directories or folders.

The way to access files through a filepath can be through the **absolute** filepath or the **relative** filepath. (We focus on relative)

My data

<center>
<img src="
https://raw.githubusercontent.com/SusannaLange/Data_118_images/main/DSSI_images/DataFrames/file_paths1.png" alt="File_paths_1" width="800">
</center>

Notebook to read in data
<center>
<img src="
https://raw.githubusercontent.com/SusannaLange/Data_118_images/main/DSSI_images/DataFrames/file_paths_2.png" alt="File paths 2" width="800">
</center>

**From where our notebook is located: we write the relative path**

'data/chicago_listings.csv'

#### Another possibility

My data
<center>
<img src="
https://raw.githubusercontent.com/SusannaLange/Data_118_images/main/DSSI_images/DataFrames/new_path.png" alt="File paths" width="800">
</center>

Notebook to read in data

<center>
<img src="
https://raw.githubusercontent.com/SusannaLange/Data_118_images/main/DSSI_images/DataFrames/file_paths_2.png" alt="File paths 2" width="800">
</center>

**From where our notebook is located: a relative path**

'../chicago_listings.csv'

### Summary

 - To navigate one directory up in a filepath, the notation
 ```python
../
```

 - To go into a folder
 ```python
/folder_name
```

<center>
<img src="
https://raw.githubusercontent.com/SusannaLange/Data_118_images/main/DSSI_images/DataFrames/csv_image.png" alt="chicagoairbnb CSV" width="800">
</center>

<code style="background:Thistle;color:black">Task: Find the data 'chicago_listings.csv' using your setup.</code>

In [ ]:
chicago_airbnb_df = pd.read_csv(????)
chicago_airbnb_df

,id,name,host_id,host_name,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2384,"Hyde Park - Walk to UChicago, 10 min to McCormick",2613,Rebecca,Hyde Park,41.78790,-87.58780,Private room,60,2,178,2019-12-15,2.56,1,353
1,4505,394 Great Reviews. 127 y/o House. 40 yds to tr...,5775,Craig & Kathleen,South Lawndale,41.85495,-87.69696,Entire home/apt,105,2,395,2020-07-14,2.81,1,155
2,7126,Tiny Studio Apartment 94 Walk Score,17928,Sarah,West Town,41.90289,-87.68182,Entire home/apt,60,2,384,2020-03-08,2.81,1,321
3,9811,Barbara's Hideaway - Old Town,33004,At Home Inn,Lincoln Park,41.91769,-87.63788,Entire home/apt,65,4,49,2019-10-23,0.63,9,300
4,10610,3 Comforts of Cooperative Living,2140,Lois,Hyde Park,41.79612,-87.59261,Private room,21,1,44,2020-02-14,0.61,5,168
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6392,45514091,Best view of Chicago downtown + optional parking,367907062,Melanie And Ryan,Near South Side,41.85574,-87.62507,Entire home/apt,146,2,0,NaN,NaN,4,180
6393,45514389,Luxurious 3Br/2Ba with optional parking and View,367907062,Melanie And Ryan,Near South Side,41.85561,-87.62342,Entire home/apt,195,2,0,NaN,NaN,4,180
6394,45514632,Two story Penthouse w private Rooftop & Great ...,367907062,Melanie And Ryan,Near South Side,41.85584,-87.62404,Entire home/apt,493,2,0,NaN,NaN,4,177
6395,45515281,West Town Private Room,347064639,Ali,West Town,41.89005,-87.66668,Private room,53,32,0,NaN,NaN,1,83
6396,45515581,Chicago Themed Private Garden Apartment,19541995,Kendal,Douglas,41.82964,-87.62048,Entire home/apt,61,1,0,NaN,NaN,1,170

More about this data: This data is from Airbnb Open Data. It contains information from Chicago in 2017-2019. Column names and what they mean are given below.

id - The id of the airbnb

name - The name of the airbnb

host_id - The id of the host

host_name - The name of the host

neighborhood - Which area is the airbnb belongs to

latitude - The latitude of the position

longitude - The longitude of the position

room_type - Entire home/apt, Private room or Other

price - The price of the apartment(per day)

minimum_nights - The least nights you need to book

number_of_reviews - The total number of the reviews on this dataset

last_review - The last review time

reviews_per_month - How many reviews the airbnb can receive per month

calculated_host_listings_count - The total listing number of the host

availability_365 - The available days

In [ ]:
small_chicago

     id   neighbourhood  price     room type
a  2384       Hyde Park     60  private room
b  4505  South Lawndale    105   entire home
c  7126       West Town     60   entire home

### Now we have a DataFrame. What can we do with it?!

### Basic stuff first

In [ ]:
chicago_airbnb_df.head(2)

,id,name,host_id,host_name,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2384,"Hyde Park - Walk to UChicago, 10 min to McCormick",2613,Rebecca,Hyde Park,41.78790,-87.58780,Private room,60,2,178,2019-12-15,2.56,1,353
1,4505,394 Great Reviews. 127 y/o House. 40 yds to tr...,5775,Craig & Kathleen,South Lawndale,41.85495,-87.69696,Entire home/apt,105,2,395,2020-07-14,2.81,1,155

## Attributes: Properties of DataFrames

In [ ]:
#We could ask for the shape - dimensions - of the DataFrame
chicago_airbnb_df.shape

(6397, 15)

In [ ]:
#We could find how many rows.
#This isn't a method or attribute though....
len(chicago_airbnb_df)

6397

In [ ]:
chicago_airbnb_df.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood', 'latitude',
       'longitude', 'room_type', 'price', 'minimum_nights',
       'number_of_reviews', 'last_review', 'reviews_per_month',
       'calculated_host_listings_count', 'availability_365'],
      dtype='object')

Common DataFrame Attributes

```python
.shape

.columns

.index
```

## DataFrame Extraction

In [ ]:
#We can extract an entire column!
small_chicago['neighbourhood']

a         Hyde Park
b    South Lawndale
c         West Town
Name: neighbourhood, dtype: object

In [ ]:
## There is often more than one way to do something
small_chicago.neighbourhood

a         Hyde Park
b    South Lawndale
c         West Town
Name: neighbourhood, dtype: object

In [ ]:
#Is this a series or a DataFrame?
type(small_chicago['neighbourhood'])

pandas.core.series.Series

What if I wanted to extract as a DataFrame?!

In [ ]:
small_chicago[['neighbourhood']]

    neighbourhood
a       Hyde Park
b  South Lawndale
c       West Town

In [ ]:
## Can we extract multiple columns?!
small_chicago[['id', 'neighbourhood']]

     id   neighbourhood
a  2384       Hyde Park
b  4505  South Lawndale
c  7126       West Town

### We can extract a single element

In [ ]:
small_chicago['id'][0]

2384

## Above we extracted columns...What about rows?

In [ ]:
#You can also choose rows by slicing
small_chicago[1:3] #starting at index 1 up to and excluding index 3

     id   neighbourhood  price    room type
b  4505  South Lawndale    105  entire home
c  7126       West Town     60  entire home

In [ ]:
small_chicago[0:3:2]

     id neighbourhood  price     room type
a  2384     Hyde Park     60  private room
c  7126     West Town     60   entire home

In [ ]:
#combining this with column extraction
small_chicago[['id', 'neighbourhood']][0:3:2]

     id neighbourhood
a  2384     Hyde Park
c  7126     West Town

## What did we just say?

Basic descriptions of DataFrame:

```python

dataframe.head()

dataframe.columns

dataframe.shape

len(dataframe)

```

We can use basic extraction to extract an entire column with either of the following:
```python

dataframe.column_name

dataframe['column_name']
```

We can extract rows with
```python

dataframe[start:end] # giving us rows [start, end)
```

We can extract multiple columns by:
   ```python
dataframe[['col_name1', 'col_name2']]
```

## Methods
We can perform many *methods* on DataFrames!

What are methods again?

*Methods* are particular built-in functions that work on objects in python. There are specific methods that work for all DataFrame objects!

Methods for DataFrames take the form
```python
df.method()
```

## Selecting based on label, integer index, and condition (More extraction techniques)

The `.loc[]` method is a label-based selection method that can subset dataframes


This `.iloc[]` method is integer-based (index based) selection method.

In [ ]:
small_chicago.loc['a','id'] #row label and column label

2384

In [ ]:
small_chicago.loc[['a', 'c'],'id']

a    2384
c    7126
Name: id, dtype: int64

In [ ]:
small_chicago.loc['a':'c','id':'price']

     id   neighbourhood  price
a  2384       Hyde Park     60
b  4505  South Lawndale    105
c  7126       West Town     60

### '.iloc'

In [ ]:
small_chicago.iloc[0,0]

2384

In [ ]:
small_chicago.iloc[0:2, 0:3]#rows first, then columns

     id   neighbourhood  price
a  2384       Hyde Park     60
b  4505  South Lawndale    105

### Extract by condition

Dataframes can also be selected based on condition using the `.loc[]` method.

That is, based on conditions that equate to `True` Boolean values.

In [ ]:
#loc uses the above to keep only those rows that are "True"
small_chicago.loc[small_chicago.neighbourhood == 'Hyde Park']

     id neighbourhood  price     room type
a  2384     Hyde Park     60  private room

In [ ]:
small_chicago.neighbourhood == 'Hyde Park' #we need double = here bc single = is for assignment

a     True
b    False
c    False
Name: neighbourhood, dtype: bool

In [ ]:
#as usual, there's alternative syntax to do this
small_chicago['neighbourhood'] == 'Hyde Park'

a     True
b    False
c    False
Name: neighbourhood, dtype: bool

In [ ]:
small_chicago.loc[small_chicago.neighbourhood == 'Hyde Park']

     id neighbourhood  price     room type
a  2384     Hyde Park     60  private room

### Note these two options produce the same result!

You can choose which one you like best.

```python

small_chicago.loc[small_chicago.neighbourhood == 'Hyde Park']

small_chicago[small_chicago.neighbourhood == 'Hyde Park']
```

You can subset on multiple conditions with the use of bitwise operators:

    & for and
    
    | for or

These perform element-wise logical 'and' 'or' operations

Suppose I am interested in...

an Airbnb in Hyde Park **or** an Airbnb less than $80

```python
(small_chicago.neighbourhood == 'Hyde Park') | (small_chicago.price < 80)
```


(It evaluates the truth value of each column of the original DataFrame)

In [ ]:
(small_chicago.neighbourhood == 'Hyde Park') | (small_chicago.price < 80)

a     True
b    False
c     True
dtype: bool

In [ ]:
small_chicago.loc[(small_chicago.neighbourhood == 'Hyde Park') | (small_chicago.price < 80)]

     id neighbourhood  price     room type
a  2384     Hyde Park     60  private room
c  7126     West Town     60   entire home

Suppose I am interested in...

an Airbnb in Hyde Park **and** an Airbnb less than $80

In [ ]:
small_chicago.loc[(small_chicago.neighbourhood == 'Hyde Park') & (small_chicago.price < 80)]

     id neighbourhood  price     room type
a  2384     Hyde Park     60  private room

## <code style="background:Thistle;color:black">Code Comprehension</code>

**Question 1:** Let's look at all of our data. How many airbnb's are in the Lincoln Park neighbourhood that have an Entire home/apt?

In [ ]:
chicago_airbnb_df.head(3)

NameError: name 'chicago_airbnb_df' is not defined

In [ ]:
#code here

<details><summary><button>Answer here. Click to reveal. </button></summary>
<p>
260
</p>
</details>

**Question 2:** Of these, how many also have at least 75 reviews?

In [ ]:
#code here

<details><summary><button>Answer here. Click to reveal. </button></summary>
<p>
61
</p>
</details>

## Some methods help us clean the data!

In [ ]:
small_chicago.rename(columns = {"neighbourhood":"neighborhood"})

     id    neighborhood  price     room type
a  2384       Hyde Park     60  private room
b  4505  South Lawndale    105   entire home
c  7126       West Town     60   entire home

#### Did this change the original DataFrame?!

In [ ]:
small_chicago

     id   neighbourhood  price     room type
a  2384       Hyde Park     60  private room
b  4505  South Lawndale    105   entire home
c  7126       West Town     60   entire home

In [ ]:
small_chicago.rename(columns = {"neighbourhood":"neighborhood"}, inplace = True)
small_chicago

     id    neighborhood  price     room type
a  2384       Hyde Park     60  private room
b  4505  South Lawndale    105   entire home
c  7126       West Town     60   entire home

In [ ]:
#OR this works if inplace = True is not an argument to the given method

#small_chicago = small_chicago.rename(columns = {"neighbourhood":"neighborhood"})
#small_chicago

     id    neighborhood  price     room type
a  2384       Hyde Park     60  private room
b  4505  South Lawndale    105   entire home
c  7126       West Town     60   entire home

## A note about overwriting DataFrames and being careful

In [ ]:
small_chicago_2 = small_chicago

In [ ]:
small_chicago_2.iloc[0] = 3
small_chicago_2

    neighbourhood  price (USD)    room type
a               3            3            3
b  South Lawndale          105  entire home
c       West Town           60  entire home

In [ ]:
small_chicago

    neighbourhood  price (USD)    room type
a               3            3            3
b  South Lawndale          105  entire home
c       West Town           60  entire home

In [ ]:
#we need to define this again bc our original is lost!
small_chicago = pd.DataFrame(
    { 'id':[2384,4505,7126],  #ID
      'neighbourhood':['Hyde Park','South Lawndale','West Town'], #neighbourhood
     'price':[60,105,60], #price
    'room type':['private room', 'entire home', 'entire home']}, index=['a','b','c']) #room_type

small_chicago

     id   neighbourhood  price     room type
a  2384       Hyde Park     60  private room
b  4505  South Lawndale    105   entire home
c  7126       West Town     60   entire home

In [ ]:
small_chicago_3 = small_chicago.copy(deep= True)
small_chicago_3.iloc[0] = 3
small_chicago_3

     id   neighbourhood  price    room type
a     3               3      3            3
b  4505  South Lawndale    105  entire home
c  7126       West Town     60  entire home

In [ ]:
small_chicago

     id   neighbourhood  price     room type
a  2384       Hyde Park     60  private room
b  4505  South Lawndale    105   entire home
c  7126       West Town     60   entire home

In [ ]:
#We could drop a column (or columns) of the data
small_chicago_clean = small_chicago.copy(deep= True)
small_chicago_clean = small_chicago_clean.drop(columns=['id'])
small_chicago_clean

    neighbourhood  price     room type
a       Hyde Park     60  private room
b  South Lawndale    105   entire home
c       West Town     60   entire home

### What about missing data? Or data not input correctly?

In [ ]:
chicago_airbnb_df.describe()

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
count,6.397000e+03,6.397000e+03,6397.000000,6397.000000,6397.000000,6397.000000,6397.000000,5265.000000,6397.000000,6397.000000
mean,2.813857e+07,9.850262e+07,41.899049,-87.664042,153.020009,8.113178,42.753791,1.745280,13.598718,174.272159
std,1.288337e+07,9.990222e+07,0.058929,0.042414,376.207706,22.786856,67.051609,1.745491,37.180574,138.877601
min,2.384000e+03,2.140000e+03,41.647360,-87.846810,0.000000,1.000000,0.000000,0.020000,1.000000,0.000000
25%,1.875555e+07,1.705221e+07,41.872740,-87.687460,64.000000,1.000000,2.000000,0.430000,1.000000,36.000000
50%,2.994743e+07,5.738786e+07,41.901860,-87.660880,99.000000,2.000000,15.000000,1.230000,2.000000,161.000000
75%,3.959279e+07,1.580558e+08,41.939780,-87.633160,155.000000,3.000000,56.000000,2.570000,7.000000,329.000000
max,4.551558e+07,3.679071e+08,42.022510,-87.537520,10000.000000,500.000000,632.000000,32.430000,205.000000,365.000000

In [ ]:
chicago_airbnb_df.loc[chicago_airbnb_df.price >=5000]

,id,name,host_id,host_name,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
648,8053583,Single Bedroom in Wicker Park Modern Mansion,3573488,Kristina,West Town,41.90800,-87.67366,Private room,10000,20,30,2019-06-16,0.49,1,358
1245,15287352,Wrigleyville Mansion - Sleeps 16+,45401863,Joe,Lake View,41.95112,-87.67020,Entire home/apt,9999,7,16,2018-11-23,0.40,2,80
1707,19643452,Large 1 bedroom with Private Bath,4404730,Kyle,Lake View,41.93917,-87.64982,Private room,9999,80,2,2017-08-08,0.05,1,363
3938,35421741,"BIG Unit, Wrigleyville, Step to Wrigley, Metro",34697612,Harry,Lake View,41.95100,-87.65785,Entire home/apt,9000,2,0,NaN,NaN,1,365
4144,36667074,Steps from Mag Mile - King Bed Boutique Hotel,265201380,St Jane,Loop,41.88714,-87.62413,Hotel room,9999,1,32,2020-03-22,2.27,3,168
4145,36668214,Steps from Mag Mile -Suite in Boutique Hotel,265201380,St Jane,Loop,41.88607,-87.62443,Hotel room,9999,1,3,2019-08-25,0.22,3,173
4146,36668235,Steps from Mag Mile - 2 Queen Beds Boutique Hotel,265201380,St Jane,Loop,41.88621,-87.62385,Hotel room,9999,1,22,2020-03-10,1.59,3,173
5558,42566731,"The Robey, Urban King Accessible",317101665,The Robey Hotel,West Town,41.91142,-87.67735,Private room,7000,1,0,NaN,NaN,8,365

We see some concerning values! For your project,

- Check codebook, see if there are values set as NaN.

- Confirm with your mentor/external mentor if these values are important.

- Don't just drop them without considering the consequences.

### We can use the .isnull() method to check for NaN values in specific columns

In [ ]:
chicago_airbnb_df[chicago_airbnb_df['last_review'].isnull()].head()

,id,name,host_id,host_name,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
87,789429,Guest bedroom with private bath,1185573,Graz Anton,Uptown,41.96193,-87.66238,Private room,99,365,0,NaN,NaN,3,365
113,1129741,Large modern apartment near CTA,4778146,Mila,East Garfield Park,41.88282,-87.72026,Entire home/apt,80,7,0,NaN,NaN,1,0
156,1755737,"Lake View 2BR/2Bath w/ Pool, Gym. Annual lease.",9233414,Ravi,Lake View,41.94036,-87.64068,Entire home/apt,155,365,0,NaN,NaN,1,363
161,1852665,BIG LOFT Location RIVER WEST Brick,3965428,Rob,Near West Side,41.88575,-87.65052,Entire home/apt,140,60,0,NaN,NaN,73,365
267,3423436,Budget travel at Great Location,17217012,Janet,Lake View,41.94177,-87.65147,Private room,70,2,0,NaN,NaN,2,88

Note: This is just the very start of the 'cleaning' process and in general includes making sure data is

   - accurate
    
   - complete
    
   - consistent

## Besides looking for NaN or missing data...we might have inconsistent data

In [ ]:
#ignore this code, suppose we start with this data below!
small_chicago_messy = small_chicago_clean.copy(deep=True)
small_chicago_messy.loc['c', 'room type'] = 'Entire home'
small_chicago_messy

    neighbourhood  price     room type
a       Hyde Park     60  private room
b  South Lawndale    105   entire home
c       West Town     60   Entire home

**How should we fix this??**

Talk to your neighbor and come up with a plan.

<details><summary><button>Possible solution here </button></summary>
<p>
Don't look until you've tried!!
</p>
</details>

<details><summary><button>Another possible solution. </button></summary>
<p>
small_chicago_messy['room type'] = small_chicago_messy['room type'].str.lower()
small_chicago_messy
</p>
</details>

## Sorting rows by values

Another important method to explore the data

using the sort_values method
```python
.sort_values()
```

This method takes the *argument* of how we want to sort the data

In [ ]:
#Default sort is ascending
small_chicago_clean.sort_values(by='price')

    neighbourhood  price     room type
a       Hyde Park     60  private room
c       West Town     60   entire home
b  South Lawndale    105   entire home

In [ ]:
#Can override that default if you like
small_chicago_clean.sort_values(by='price', ascending=False)

    neighbourhood  price     room type
b  South Lawndale    105   entire home
a       Hyde Park     60  private room
c       West Town     60   entire home

### Operations to summarize the data!

In [ ]:
np.mean(small_chicago_clean['price'])  #series

75.0

In [ ]:
np.mean(small_chicago_clean[['price']])  #dataframe

75.0

Here's a short list of methods that can be used to determine summative information and/or statistics:

`.min()` - determines the minimum value in a dataframe/series

`.max()` - determines the maximum value in a dataframe/series

`.mean()` - determines the mean value of a dataframe/series

`.median()` - determines the median value in a dataframe/series

`.sum()` - determines the sum of the values in a dataframe/series

`.mode()` - determines the mode of a dataframe/series

`.nlargest()` - determines the largest *n* items in a series. (Default = 5)

`.nsmallest()` - determines the smallest *n* items in a series. (Default = 5)

`.count()` - counts all non-null items in a dataframe/series

`.value_counts` - counts the number of times an item occurs in a dataframe/series

`.nunique()` - counts the number of unique items in a dataframe/series

`.unique()` - lists all of the unique items in a dataframe/series

`.describe` - generates descriptive statistics of a dataframe column, including those that summarize the central tendency, dispersion and shape of a dataset’s distribution, excluding null values (NaN).

## Let's summarize some of what we've done so far

Some important attributes and methods of DataFrames:

 - .columns

 - .shape

 - .drop()

 - .mean()

 - sort.values(by=...)

### We can extract slices of our DataFrame based on

 - label --------> .loc

 - based on index --------> .iloc

 - based on condition

Note: This is an incomplete collection of a few commonly used methods. To see more [Link to Documentation: DataFrame methods/attributes](https://pandas.pydata.org/docs/reference/frame.html)

### <mark style="background-color: Thistle"> Code comprehension: Activity</mark>

Let's explore the bigger chicago airbnb dataset!

In [ ]:
## download the dataset from Canvas and load it in here
chicago_airbnb_df.head(2)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2384,"Hyde Park - Walk to UChicago, 10 min to McCormick",2613,Rebecca,NaN,Hyde Park,41.78790,-87.58780,Private room,60,2,178,2019-12-15,2.56,1,353
1,4505,394 Great Reviews. 127 y/o House. 40 yds to tr...,5775,Craig & Kathleen,NaN,South Lawndale,41.85495,-87.69696,Entire home/apt,105,2,395,2020-07-14,2.81,1,155

## Question 1: What does the below line of code do?

In [ ]:
#run this line of code
chicago_airbnb_df.tail() #is there a default if the argument is empty?

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
6392,45514091,Best view of Chicago downtown + optional parking,367907062,Melanie And Ryan,NaN,Near South Side,41.85574,-87.62507,Entire home/apt,146,2,0,NaN,NaN,4,180
6393,45514389,Luxurious 3Br/2Ba with optional parking and View,367907062,Melanie And Ryan,NaN,Near South Side,41.85561,-87.62342,Entire home/apt,195,2,0,NaN,NaN,4,180
6394,45514632,Two story Penthouse w private Rooftop & Great ...,367907062,Melanie And Ryan,NaN,Near South Side,41.85584,-87.62404,Entire home/apt,493,2,0,NaN,NaN,4,177
6395,45515281,West Town Private Room,347064639,Ali,NaN,West Town,41.89005,-87.66668,Private room,53,32,0,NaN,NaN,1,83
6396,45515581,Chicago Themed Private Garden Apartment,19541995,Kendal,NaN,Douglas,41.82964,-87.62048,Entire home/apt,61,1,0,NaN,NaN,1,170

Answer here

## Question 2: Print out all the columns in this dataset

In [ ]:
#code here

## Question 3: How many neighbourhoods are included in this data?

In [ ]:
#code here

## Question 4: Find the average price of a day stay.

In [ ]:
#code here

## Question 5: How many different room types are available? What are they?

In [ ]:
#code here

## Question 6: Find the maximum number of reviews of a single Airbnb.

In [ ]:
#code here

Yay! This notebook is now complete. 😎