<center> 

# DSSI: Summer 2024
    
## DataFrame Operations
### Groupby and Pivot_table

#### Authored by: Susanna Lange, PhD

<center>
<img src="https://raw.githubusercontent.com/amandakube/Data118LectureImages/main/UChicago_DSI.png" alt="UC-DSI" width="300" height="100">
</center>

In [ ]:
import numpy as np
import pandas as pd

## Focus of this notebook

DataFrame Methods (Operations)

- grouping by specific columns

    - ```.groupby()```
    
- pivot table

    - ```.pivot_table()```

## Back to AirBnB Data...

In [ ]:
chicago_airbnb_df = pd.read_csv('data/chicago_listings.csv')
chicago_airbnb_df.head(3)

,id,name,host_id,host_name,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2384,"Hyde Park - Walk to UChicago, 10 min to McCormick",2613,Rebecca,Hyde Park,41.78790,-87.58780,Private room,60,2,178,2019-12-15,2.56,1,353
1,4505,394 Great Reviews. 127 y/o House. 40 yds to tr...,5775,Craig & Kathleen,South Lawndale,41.85495,-87.69696,Entire home/apt,105,2,395,2020-07-14,2.81,1,155
2,7126,Tiny Studio Apartment 94 Walk Score,17928,Sarah,West Town,41.90289,-87.68182,Entire home/apt,60,2,384,2020-03-08,2.81,1,321

### Does average price of a Chicago AirBnB differ by neighborhood??

In [ ]:
chicago_airbnb_df.neighbourhood.unique()

array(['Hyde Park', 'South Lawndale', 'West Town', 'Lincoln Park',
       'Near North Side', 'Logan Square', 'Uptown', 'North Center',
       'Lake View', 'Irving Park', 'Portage Park', 'Pullman',
       'Near South Side', 'West Ridge', 'Near West Side', 'Edgewater',
       'Bridgeport', 'Woodlawn', 'Albany Park', 'Kenwood', 'Avondale',
       'Rogers Park', 'Lincoln Square', 'Grand Boulevard', 'Forest Glen',
       'Loop', 'East Garfield Park', 'North Lawndale', 'Oakland',
       'Beverly', 'Lower West Side', 'Chatham', 'Mckinley Park',
       'Norwood Park', 'Washington Park', 'Humboldt Park', 'Morgan Park',
       'Dunning', 'West Lawn', 'South Shore', 'Armour Square',
       'South Deering', 'West Garfield Park', 'Hermosa', 'Douglas',
       'Hegewisch', 'North Park', 'Jefferson Park', 'West Elsdon',
       'Austin', 'Ashburn', 'Belmont Cragin', 'Greater Grand Crossing',
       'Garfield Ridge', 'Brighton Park', 'Archer Heights', 'Ohare',
       'Edison Park', 'Englewood', 'South Chicago', 'Avalon Park',
       'Chicago Lawn', 'Gage Park', 'Montclare', 'Clearing', 'Roseland',
       'Calumet Heights', 'New City', 'Fuller Park', 'Auburn Gresham',
       'West Pullman', 'West Englewood', 'Washington Heights', 'Burnside',
       'Mount Greenwood', 'Riverdale', 'East Side'], dtype=object)

## Goal: Aggregate statistics

Often, we want to compute aggregate statistics over row

The `groupby` function allows us to split the DataFrame into groups.

 - We can group data into new DataFrames
 - We can apply a method to groups of data

The most important input to this function is what we are grouping *by*, a column name. The general format of the `groupby` operation is given by:

```python
df.groupby(by='group_name')
```

In [ ]:
chicago_grouped_nb= chicago_airbnb_df.groupby('neighbourhood')
chicago_grouped_nb

In [ ]:
chicago_airbnb_df.groupby('neighbourhood').mean(numeric_only=True)

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
neighbourhood,,,,,,,,,,
Albany Park,2.760048e+07,9.036109e+07,41.967850,-87.715912,88.000000,6.955882,36.514706,1.615161,2.838235,138.735294
Archer Heights,2.498435e+07,1.179491e+08,41.805178,-87.724542,82.833333,1.500000,92.000000,2.453333,1.333333,227.666667
Armour Square,2.839555e+07,1.577492e+08,41.850035,-87.633804,132.940299,1.447761,56.985075,2.104167,9.597015,192.731343
Ashburn,3.424856e+07,1.749252e+08,41.741620,-87.702515,71.307692,3.307692,21.769231,1.456000,2.461538,166.000000
Auburn Gresham,3.369399e+07,1.174524e+08,41.747087,-87.653883,125.166667,2.333333,1.333333,0.127500,2.000000,113.833333
...,...,...,...,...,...,...,...,...,...,...
West Lawn,2.631949e+07,1.342746e+08,41.773948,-87.724837,37.900000,1.800000,129.400000,3.462222,2.000000,163.000000
West Pullman,3.711405e+07,2.020320e+08,41.671330,-87.652770,95.000000,1.500000,1.000000,0.090000,2.500000,298.500000
West Ridge,2.660318e+07,1.050176e+08,42.002615,-87.693418,85.608696,4.681159,30.869565,1.284737,3.101449,164.275362
West Town,2.554971e+07,7.480435e+07,41.901556,-87.675244,179.348966,5.383448,56.943448,1.897633,5.051034,146.656552
Woodlawn,2.791226e+07,6.651950e+07,41.781666,-87.603650,69.702381,6.809524,41.690476,1.406000,5.869048,216.166667

In [ ]:
chicago_airbnb_df.groupby('neighbourhood').mean(numeric_only=True)[['price']]

                     price
neighbourhood
Albany Park      88.000000
Archer Heights   82.833333
Armour Square   132.940299
Ashburn          71.307692
Auburn Gresham  125.166667
...                    ...
West Lawn        37.900000
West Pullman     95.000000
West Ridge       85.608696
West Town       179.348966
Woodlawn         69.702381

[77 rows x 1 columns]

## What can I aggregate by?

**Common Aggregate Functions**

.count() – Number of observations

.sum() – Sum of values

.mean() – Mean of values

.median() – Arithmetic median of values

.min() – Minimum

.max() – Maximum

.mode() – Mode

.std() – Standard deviation

.var() – Variance

**How many AirBnBs are in each neighborhood?**

In [ ]:
chicago_airbnb_df.groupby('neighbourhood').count()

,id,name,host_id,host_name,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
neighbourhood,,,,,,,,,,,,,,
Albany Park,68,68,68,68,68,68,68,68,68,68,62,62,68,68
Archer Heights,6,6,6,6,6,6,6,6,6,6,6,6,6,6
Armour Square,67,67,67,67,67,67,67,67,67,67,60,60,67,67
Ashburn,13,13,13,13,13,13,13,13,13,13,10,10,13,13
Auburn Gresham,6,6,6,6,6,6,6,6,6,6,4,4,6,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
West Lawn,10,10,10,10,10,10,10,10,10,10,9,9,10,10
West Pullman,2,2,2,2,2,2,2,2,2,2,1,1,2,2
West Ridge,69,69,69,69,69,69,69,69,69,69,57,57,69,69
West Town,725,725,725,725,725,725,725,725,725,725,638,638,725,725
Woodlawn,84,84,84,84,84,84,84,84,84,84,75,75,84,84

**What is the minimum price by neighborhood?**

In [ ]:
grouped_nb_min = chicago_airbnb_df.groupby('neighbourhood').min(numeric_only=True)[['price']]
grouped_nb_min

                price
neighbourhood
Albany Park        23
Archer Heights     36
Armour Square      17
Ashburn            29
Auburn Gresham     59
...               ...
West Lawn          25
West Pullman       90
West Ridge         19
West Town          26
Woodlawn           26

[77 rows x 1 columns]

Does this change the way we extract elements?

In [ ]:
grouped_nb_min.price['Albany Park']

23

Notice we have a DataFrame with a column name as an index. If we don't want that, we can use a method
```python
.reset_index()
```

In [ ]:
grouped_nb_min.reset_index()

     neighbourhood  price
0      Albany Park     23
1   Archer Heights     36
2    Armour Square     17
3          Ashburn     29
4   Auburn Gresham     59
..             ...    ...
72       West Lawn     25
73    West Pullman     90
74      West Ridge     19
75       West Town     26
76        Woodlawn     26

[77 rows x 2 columns]

### We can group by multiple columns

Notice the row indexes are constructed from both grouping columns

In [ ]:
chicago_airbnb_df.groupby(['neighbourhood', 'room_type']).count()[['id']]

                                 id
neighbourhood  room_type
Albany Park    Entire home/apt   30
               Private room      38
Archer Heights Entire home/apt    3
               Private room       3
Armour Square  Entire home/apt   30
...                             ...
West Town      Hotel room        18
               Private room     205
               Shared room        4
Woodlawn       Entire home/apt   28
               Private room      56

[182 rows x 1 columns]

We would use tables like this for cross-classification - looking at patterns between variables

Let's use a **pivot_table**!

## General Pivot_table
A *pivot_table* allows for cross-classification of groups in a DataFrame.

The general format for a *pivot_table* is –

```python
df.pivot_table(values = 'data', index='group_1', columns='group_2', aggfunc='function')
```

– where:

* each unique value in `index` gets its own row

* each unique value in `columns` gets its own column

* and `data` specifies the value in the DataFrame to which we want to apply `aggfunc`

The default option for `aggfunc` is `mean`.

In [ ]:
chicago_airbnb_df.pivot_table(values = 'price', index = 'neighbourhood', columns = 'room_type', aggfunc = 'mean')

room_type       Entire home/apt  Hotel room  Private room  Shared room
neighbourhood
Albany Park          135.166667         NaN     50.763158          NaN
Archer Heights        89.000000         NaN     76.666667          NaN
Armour Square        239.800000         NaN     46.297297          NaN
Ashburn               99.428571         NaN     38.500000          NaN
Auburn Gresham       229.500000         NaN     73.000000          NaN
...                         ...         ...           ...          ...
West Lawn             51.666667         NaN     32.000000          NaN
West Pullman          90.000000         NaN    100.000000          NaN
West Ridge           127.909091         NaN     52.033333    20.833333
West Town            189.951807  141.388889    158.756098    85.500000
Woodlawn             117.785714         NaN     45.660714          NaN

[77 rows x 4 columns]

We can use the argument `fill_value` to replace those NaN values with 0 since no airbnb's in those groups.

In [ ]:
chicago_airbnb_df.pivot_table(values = 'price', index = 'neighbourhood', columns = 'room_type', aggfunc = 'mean', fill_value = 0)

room_type       Entire home/apt  Hotel room  Private room  Shared room
neighbourhood
Albany Park          135.166667    0.000000     50.763158     0.000000
Archer Heights        89.000000    0.000000     76.666667     0.000000
Armour Square        239.800000    0.000000     46.297297     0.000000
Ashburn               99.428571    0.000000     38.500000     0.000000
Auburn Gresham       229.500000    0.000000     73.000000     0.000000
...                         ...         ...           ...          ...
West Lawn             51.666667    0.000000     32.000000     0.000000
West Pullman          90.000000    0.000000    100.000000     0.000000
West Ridge           127.909091    0.000000     52.033333    20.833333
West Town            189.951807  141.388889    158.756098    85.500000
Woodlawn             117.785714    0.000000     45.660714     0.000000

[77 rows x 4 columns]

### What have we seen so far?

```python

df.groupby(by='group_name')

df.pivot_table(data, index='group_1', columns='group_2', aggfunc='function')

.reset_index()
```

**Common Aggregate Functions**

.count() – Number of non-null observations

.sum() – Sum of values

.mean() – Mean of values

.median() – Arithmetic median of values

.min() – Minimum

.max() – Maximum

.mode() – Mode

.std() – Standard deviation

.var() – Variance

### <code style="background:Thistle;color:black">Using these operations in practice.</code>


The Illinois Department of Transportation (IDOT) collects records of all traffic stops made by CPD. We've provided data on all stops made in the years 2017 - 2018.

Using the IDOT data on Canvas answer the following questions:

In [ ]:
# Read in data here and print out the first few rows to see what the data looks like!

### Question 1. How many stops occurred for each race in each year?

In [ ]:
# Your code here

<details><summary><button>Partial answer here. </button></summary>
<p>
You should end up with an entire DataFrame that displays the answer! For a quick sanity check, you'll find that in 2017, there were 7249 stoped who identify as asian, 59557 who identify as hispanic.
</p>
</details>

### Question 2. Across all years, which racial group was stopped most often?

In [ ]:
# Your code here

<details><summary><button>Hint </button></summary>
<p>
Since now we are looking across years and dont care what year it is, we no longer need to group by year as well
Since we are only grouping by one thing this is no longer cross-classification so we use groupby
</p>
</details>

### Question 3. Stop rates are more useful than counts. Using the table you made in Q2 and what you know about indexing dataframes, calculate the stop rate (percentage of total stops) for each racial group.

In [ ]:
# Your code here

## Are these stops racially biased?

Maybe there are just more drivers...

We need some way to compare. We would need more data!