<center> 

# DSSI: Summer 2024
    
## User Defined Functions 

#### Authored by: Bill Trok

<center>
<img src="https://raw.githubusercontent.com/amandakube/Data118LectureImages/main/UChicago_DSI.png" alt="UC-DSI" width="300" height="100">
</center>

In [ ]:
import numpy as np
import pandas as pd

%matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

## Today

* Functions
* Apply

# Functions

Often we find while programming that there is code we want to reuse.

For instance, maybe we are combining data temperature data sets some of which are in Fahrenheit and some are in Celsius. If we want to do any analysis we should do this in the same units. We might find we are rewriting the same code over and over again.

In [ ]:
# Temps in Fahrenheit
tempA = 33.1
tempB = 45.67
tempC = 212.0

# convert these to Celsius
print((tempA-32)*5/9)
print((tempB-32)*5/9)
print((tempC-32)*5/9)

0.6111111111111119
7.594444444444445
100.0

When we find ourselves doing this it can be useful to write our own function.

In [ ]:
def FtoC(temp):
    """Converts a temperature from Fahrenheit to Celsius"""
    return (temp-32)*9/5

In [ ]:
print(FtoC(tempA))
print(FtoC(tempB))
print(FtoC(tempC))

1.9800000000000026
24.606
324.0

One big advantage is if I made a mistake like I did above. I only have to correct it in one place.

In [ ]:
def FtoC(temp):
    """Converts a temperature from Fahrenheit to Celsius. Correctly this time."""
    return (temp-32)*5/9

In [ ]:
print(FtoC(tempA))
print(FtoC(tempB))
print(FtoC(tempC))

0.6111111111111119
7.594444444444445
100.0

The string that appears after the function definition is the doc string. This should describe what the function does, it will be returned if you call ```help``` on the function. This is useful to you and anyone else you work with on a project.

In [ ]:
help(FtoC)

Help on function FtoC in module __main__:

FtoC(temp)
    Converts a temperature from Fahrenheit to Celsius. Correctly this time.

## Warning

A common mistake when writing a doc string, is to accidentally write your doc string as a comment. Obviously this is better than no doc string, but it's not as useful, because ``help`` won't return the documentation.

In [ ]:
def FtoC(temp):
    #Converts a temperature from Fahrenheit to Celsius. Correctly this time.
    return (temp-32)*5/9
help(FtoC)

Help on function FtoC in module __main__:

FtoC(temp)

## More Complicated Functions - Multiple Parameters

Just like built-in functions we can define functions that have more than one parameter.

In [ ]:
def add(x,y):
    "returns the sum of x and y"
    return x+y

In [ ]:
add(2,3)

5

In [ ]:
help(add)

Help on function add in module __main__:

add(x, y)
    returns the sum of x and y

Note that even though you may think of add as being an operation on numbers. We can actually call add on any data types that can be added together.

In [ ]:
add("Hello ","world!")

'Hello world!'

In [ ]:
add([0,1,2],[4])

[0, 1, 2, 4]

Though in practice most of the time, it will only make sense to call a function on certain types.

In [ ]:
FtoC("Hello World!")

TypeError: unsupported operand type(s) for -: 'str' and 'int'

## More Complicated Functions - Multi-line Functions

So far all functions we have defined consisted of just a return statement. However, most of the time we will find ourselves wanting to define a function which repeats more than a single line of code.

In [ ]:
def percents(values):
    """This function takes a array of numbers and returns the proportion of the total
    that each value takes up."""
    total = sum(values)
    proportions = values/total
    return np.round(proportions*100,decimals=2)

In [ ]:
percents(np.array([2,3]))

array([40., 60.])

## Scoping - Where do names have meaning?

### INDENTATION matters in Python...

In [ ]:
def percents(values):
"""This function takes a array of numbers and returns the proportion of the total that each value takes up."""
total = sum(values)
proportions = values/total
return np.round(proportions*100,decimals=2)

IndentationError: expected an indented block after function definition on line 1 (1997575854.py, line 2)

In [ ]:
def percents(values):
    """This function takes a array of numbers and returns the proportion of the total that each value takes up."""
    proportion = values/sum(values)
    print("Hi, I'm in the function and proportion =", proportion)
    return np.round(proportion * 100,decimals=2)

In [ ]:
percents(np.array([1, 2, 3, 4]))

Hi, I'm in the function and proportion = [0.1 0.2 0.3 0.4]

array([10., 20., 30., 40.])

In [ ]:
proportion

NameError: name 'proportion' is not defined

What happens if define a variable in a function that has the same name as another variable?

In [ ]:
x = 17
def setVar(y):
    x=y
    print("x == ",x)
    return x

print("setVar",setVar(12))
print("x == ",x)

x ==  12
setVar 12
x ==  17

### Optional Arguments

Sometimes we want to have more flexibility when defining a function but also now loose the convenience of an earlier definition.

In [ ]:
def new_percents(values, places):
    """This function takes a array of numbers and returns the percent of the total that each value takes up.
    values = array of values
    places = number of decimal places to round percent to."""
    proportion = values/sum(values)
    return np.round(proportion * 100, places)

new_percents(np.array([1,2,3,43]),2)

array([ 2.04,  4.08,  6.12, 87.76])

Note: the function as written *requires* two arguments

In [ ]:
new_percents(np.array([1,2,3,43]))

TypeError: new_percents() missing 1 required positional argument: 'places'

We can make arguments optional by providing **default** values

In [ ]:
def new_percents(values, places = 2):
    """This function takes a array of numbers and returns the percent of the total that each value takes up.
    values = array of values
    places = number of decimal places to round percent to (default = 2)"""
    proportion = values/sum(values)
    return np.round(proportion * 100, places)

now the function can take one or two arguments

In [ ]:
my_array = np.array([1,2,3,43])
new_percents(my_array,4)

array([ 2.0408,  4.0816,  6.1224, 87.7551])

In [ ]:
new_percents(my_array)

array([ 2.04,  4.08,  6.12, 87.76])

You can reorder arguments by being explicit in the call

This is useful if you have multiple optional arguments

In [ ]:
new_percents(places=3, values=my_array)

array([ 2.041,  4.082,  6.122, 87.755])

## Apply - Using functions with DataFrames in Pandas

Let's define a function that replaces any numbers greater than 100 with 100

In [ ]:
def cut_off(age):
    return min(age, 100)

In [ ]:
print('adjusted age of 70 is:', cut_off(70))
print('adjusted age of 170 is:', cut_off(170))

adjusted age of 70 is: 70
adjusted age of 170 is: 100

Create a DataFrame

In [ ]:
ages = pd.DataFrame(
    {'Person': np.array(['A', 'B', 'C', 'D']),
    'Age': np.array([63, 101, 99, 102])}
)
ages

  Person  Age
0      A   63
1      B  101
2      C   99
3      D  102

### Using "apply()" on a single column

Provide the function name and the column on which to apply the function

`apply()` returns a Series

In [ ]:
ages.Age.apply(cut_off)

0     63
1    100
2     99
3    100
Name: Age, dtype: int64

Note, it is often good practice to retain the original data when you are modifying it for further analysis (so you don't lose data that may be useful in the future and you have a record of what you did.)

If you want to augment the table you need to do so explicitly

In [ ]:
ages['AgeCutoff'] = ages.Age.apply(cut_off)
ages

  Person  Age  AgeCutoff
0      A   63         63
1      B  101        100
2      C   99         99
3      D  102        100

When applying functions to dataframes it is sometimes useful to use "anonymous" (unnamed) functions.   

These are called "lambda functions".

Note, lambda functions are also handy for impressing friends and family!

Here's the above example done with a lambda function. Note this has the advantage of not having to save the cutoff function as above.

In [ ]:
ages.Age.apply(lambda x: max(x,100))

0     63
1    100
2     99
3    100
Name: Age, dtype: int64

In the above example, the `x` variable is bound to each value in the `Age` column because we called it on `ages.Age`

Note there's really very little different between lambda functions and the ordinary functions we've been defining. In fact, one could theoretically define a function using lambda functions.

In [ ]:
double = (lambda x: x*2)
double(4)

Though you should avoid doing this in part because you can't define doc strings for lambda functions, (lie) and you can't define multi line lambda functions (mostly true).

One limitation lambda functions do not have is single inputs.

In [ ]:
mult = (lambda x,y: x*y)
mult(3,7)

21

With lambda functions we can also have the variable bind to entire rows.  This is useful when your functions need to access multiple columns.

Note that we have to use `axis="columns"` (or `axis = 1`) so that the lambda function is applied to each row.

In [ ]:
ages['NewDiff'] = ages.apply(lambda x: x.Age - x.AgeCutoff,axis='columns')
ages

  Person  Age  AgeCutoff  NewDiff
0      A   63         63        0
1      B  101        100        1
2      C   99         99        0
3      D  102        100        2

Description of "axis" from the python documentation
(seems a bit counter-intuitive to me!)

**axis**: *{0 or 'index', 1 or 'columns'}, default 0*
<br>
Axis along which the function is applied:
- 0 or 'index': apply function to each column.
- 1 or 'columns': apply function to each row.