<center> 

# DSSI: Summer 2024
    
## DataFrame Operations
### Merge 

#### Authored by: Bill Trok, PhD

<center>
<img src="https://raw.githubusercontent.com/amandakube/Data118LectureImages/main/UChicago_DSI.png" alt="UC-DSI" width="300" height="100">
</center>

In [2]:
import numpy as np
import pandas as pd

## Focus of this notebook

DataFrame Methods (Operations)

- Merging Data Frames

    - ```pd.merge()```

## Warm-up

Suppose we are interested in the number of grocery stores in each Neighborhood in Chicago. Use the data below and ``groupby`` to count the number of Grocery Stores in each neighborhood of Chicago. The result should be stored in a dataframe called ``grocery_count_df``. The dataframe should have two columns one containing the counts and one containing the "COMMUNITY AREA NAME".

In [ ]:
grocery_df = pd.read_csv('data/groceries.csv')
grocery_df

,STORE NAME,LICENSE ID,ACCOUNT NUMBER,SQUARE FEET,BUFFER SIZE,ADDRESS,ZIP CODE,COMMUNITY AREA NAME,COMMUNITY AREA,WARD,CENSUS TRACT,CENSUS BLOCK,X COORDINATE,Y COORDINATE,LATITUDE,LONGITUDE,LOCATION
0,Bob'S Liquors & Groceries,957.0,86492.0,10001.0,A,5069 W Madison St,60644,Austin,25,28,17031252201,1.703125e+14,1.142425e+06,1.899505e+06,41.880296,-87.752494,"(41.8802960895, -87.7524941982)"
1,Quick Stop Food Mart,39791.0,3604.0,3000.0,B,2751 W Pratt Blvd,60645,West Ridge,2,50,17031020601,1.703102e+14,1.156543e+06,1.944959e+06,42.004750,-87.699423,"(42.0047500731, -87.6994227766)"
2,Dominick'S #147/1147,41674.0,5033.0,68000.0,A,1340 S Canal St,60607,Near West Side,28,2,17031841900,1.703184e+14,1.173296e+06,1.893986e+06,41.864521,-87.639304,"(41.8645211937, -87.6393040996)"
3,Cermak Produce,1515206.0,279468.0,25000.0,A,5220 S Pulaski Rd,60632,West Elsdon,62,23,17031620200,1.703162e+14,1.150549e+06,1.869569e+06,41.797992,-87.723444,"(41.79799187, -87.7234437408)"
4,Whole Foods Market,54059.0,86298.0,4501.0,B,3300 N Ashland Ave,60657,Lake View,6,44,17031062500,1.703106e+14,1.165028e+06,1.921997e+06,41.941566,-87.668860,"(41.9415658578, -87.6688604029)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,Walgreens #11410,1959845.0,7551.0,NaN,A,1627 N Pulaski Rd,60639,Humboldt Park,23,30,17031230400,1.703120e+14,1.149505e+06,1.910639e+06,41.910714,-87.726210,"(41.91071448, -87.72621042)"
502,Tierra Caliente Market,1769425.0,311388.0,3125.0,B,1402 N Ashland Ave,60622,West Town,24,1,17031241500,1.703124e+14,1.165430e+06,1.909441e+06,41.907102,-87.667740,"(41.9071018181, -87.6677396553)"
503,Quality Food On 71 St Inc,76481.0,22614.0,3000.0,B,2557 W 71St St,60629,Chicago Lawn,66,18,17031661000,1.703166e+14,1.160309e+06,1.857439e+06,41.764512,-87.687987,"(41.7645116769, -87.687986655)"
504,Jewel Food Store #3302,1402.0,259.0,25431.0,A,3644 S Archer Ave,60609,Mckinley Park,59,11,17031590500,1.703159e+14,1.161644e+06,1.880434e+06,41.827584,-87.682454,"(41.8275838968, -87.6824544425)"
505,Cermak Produce,1770942.0,311980.0,17000.0,A,3311 W 26Th St,60623,South Lawndale,30,22,17031840800,1.703184e+14,1.154665e+06,1.886498e+06,41.844367,-87.707898,"(41.8443667287, -87.7078980538)"

In [ ]:
# YOUR CODE HERE
grocery_count_df = ...

In [ ]:
# SOLUTION
grocery_count_df = grocery_df.groupby("COMMUNITY AREA NAME")[["STORE NAME"]].count()
grocery_count_df = grocery_count_df.reset_index()
grocery_count_df

   COMMUNITY AREA NAME  STORE NAME
0          Albany Park          12
1       Archer Heights           4
2        Armour Square           4
3              Ashburn           3
4       Auburn Gresham          11
..                 ...         ...
70           West Lawn           4
71        West Pullman           5
72          West Ridge          18
73           West Town          14
74            Woodlawn           5

[75 rows x 2 columns]

## Renaming Columns

Often we might want to rename columns of our dataframe to be more descriptive, or to follow a certain format. Remember we can do that with the rename method. Use it to rename the column containing the number of stores to "NUM STORES".

In [ ]:
grocery_count_df = grocery_count_df.rename(columns={"STORE NAME":"NUM STORES"})
grocery_count_df

   COMMUNITY AREA NAME  NUM STORES
0          Albany Park          12
1       Archer Heights           4
2        Armour Square           4
3              Ashburn           3
4       Auburn Gresham          11
..                 ...         ...
70           West Lawn           4
71        West Pullman           5
72          West Ridge          18
73           West Town          14
74            Woodlawn           5

[75 rows x 2 columns]

## Recall the  AirBnB Data

In [ ]:
chicago_airbnb_df = pd.read_csv('data/chicago_listings.csv')
chicago_airbnb_df.head(5)

,id,name,host_id,host_name,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2384,"Hyde Park - Walk to UChicago, 10 min to McCormick",2613,Rebecca,Hyde Park,41.78790,-87.58780,Private room,60,2,178,2019-12-15,2.56,1,353
1,4505,394 Great Reviews. 127 y/o House. 40 yds to tr...,5775,Craig & Kathleen,South Lawndale,41.85495,-87.69696,Entire home/apt,105,2,395,2020-07-14,2.81,1,155
2,7126,Tiny Studio Apartment 94 Walk Score,17928,Sarah,West Town,41.90289,-87.68182,Entire home/apt,60,2,384,2020-03-08,2.81,1,321
3,9811,Barbara's Hideaway - Old Town,33004,At Home Inn,Lincoln Park,41.91769,-87.63788,Entire home/apt,65,4,49,2019-10-23,0.63,9,300
4,10610,3 Comforts of Cooperative Living,2140,Lois,Hyde Park,41.79612,-87.59261,Private room,21,1,44,2020-02-14,0.61,5,168

Yesterday, we used this data to count the number of airbnbs in each neighborhood of Chicago.

In [ ]:
chicago_airbnb_df.groupby('neighbourhood')[['id']].count()

                 id
neighbourhood
Albany Park      68
Archer Heights    6
Armour Square    67
Ashburn          13
Auburn Gresham    6
...             ...
West Lawn        10
West Pullman      2
West Ridge       69
West Town       725
Woodlawn         84

[77 rows x 1 columns]

## Merge
Frequently, we will have more than one data set that we want to analyze, or we have some data we're interested in that is missing from a data set we do have. For instance, suppose we want to combine the airbnb information with information about grocery stores to get a summary of each neighborhood in Chicago.

To do this we can use the functions merge. When doing this operations, we need to give two columns which contain the same information.

In [ ]:
airbnb_count_df = chicago_airbnb_df.groupby("neighbourhood")[["name"]].count().reset_index()
airbnb_count_df = airbnb_count_df.rename(columns={"name":"num airbnbs"})
airbnb_count_df

     neighbourhood  num airbnbs
0      Albany Park           68
1   Archer Heights            6
2    Armour Square           67
3          Ashburn           13
4   Auburn Gresham            6
..             ...          ...
72       West Lawn           10
73    West Pullman            2
74      West Ridge           69
75       West Town          725
76        Woodlawn           84

[77 rows x 2 columns]

In [ ]:
pd.merge(airbnb_count_df,grocery_count_df,left_on="neighbourhood",right_on="COMMUNITY AREA NAME")

     neighbourhood  num airbnbs COMMUNITY AREA NAME  NUM STORES
0      Albany Park           68         Albany Park          12
1   Archer Heights            6      Archer Heights           4
2    Armour Square           67       Armour Square           4
3          Ashburn           13             Ashburn           3
4   Auburn Gresham            6      Auburn Gresham          11
..             ...          ...                 ...         ...
70       West Lawn           10           West Lawn           4
71    West Pullman            2        West Pullman           5
72      West Ridge           69          West Ridge          18
73       West Town          725           West Town          14
74        Woodlawn           84            Woodlawn           5

[75 rows x 4 columns]

You might notice a few things about the resulting dataframe. First, both columns "neighbourhood" and "COMMUNITY AREA NAME" are present in the data frame. Secondly, and more subtly, we actually lost data when doing this merge.

We started with 77 columns in the airbnb data, but end up with a dataset with only 75 columns.

This is explained by some default behavior of ``pd.merge``. We can retain all the data if we use the optional parameter ``how == "outer"``.

In [ ]:
comb_df = pd.merge(airbnb_count_df,grocery_count_df,left_on="neighbourhood",right_on="COMMUNITY AREA NAME",how="outer")
comb_df

     neighbourhood  num airbnbs COMMUNITY AREA NAME  NUM STORES
0      Albany Park           68         Albany Park        12.0
1   Archer Heights            6      Archer Heights         4.0
2    Armour Square           67       Armour Square         4.0
3          Ashburn           13             Ashburn         3.0
4   Auburn Gresham            6      Auburn Gresham        11.0
..             ...          ...                 ...         ...
72       West Lawn           10           West Lawn         4.0
73    West Pullman            2        West Pullman         5.0
74      West Ridge           69          West Ridge        18.0
75       West Town          725           West Town        14.0
76        Woodlawn           84            Woodlawn         5.0

[77 rows x 4 columns]

## Options for Merge

In fact there are many different options for merge. To get a sense for their behavior let's look at some simple data.

In [ ]:
fruit1 = pd.DataFrame({"Name":["Apple","Papaya","Lemon"],
                       "Avg. Weight (g)":[186,275,58],
                       "Vitamin C (g/100 ml)":[27.5,61,53]})
fruit1

     Name  Avg. Weight (g)  Vitamin C (g/100 ml)
0   Apple              186                  27.5
1  Papaya              275                  61.0
2   Lemon               58                  53.0

In [ ]:
fruit2 = pd.DataFrame({"Name":["Lemon","Apple","Apple","Orange"],
                       "Cost ($/lb)":[1.98,1.23,1.67,1.43],
                       "Color":["Yellow","Red","Green","Orange"]})
fruit2

     Name  Cost ($/lb)   Color
0   Lemon         1.98  Yellow
1   Apple         1.23     Red
2   Apple         1.67   Green
3  Orange         1.43  Orange

Note if two DataFrames have a shared column with the same name, you can just specify the one column name.
The default option for merge is ``how = "inner"``. This combines the data only including rows contained in both dataframes.

In [ ]:
pd.merge(fruit1,fruit2,left_on="Name",right_on="Name")

    Name  Avg. Weight (g)  Vitamin C (g/100 ml)  Cost ($/lb)   Color
0  Apple              186                  27.5         1.23     Red
1  Apple              186                  27.5         1.67   Green
2  Lemon               58                  53.0         1.98  Yellow

In [ ]:
pd.merge(fruit1,fruit2,on="Name",how="inner")

    Name  Avg. Weight (g)  Vitamin C (g/100 ml)  Cost ($/lb)   Color
0  Apple              186                  27.5         1.23     Red
1  Apple              186                  27.5         1.67   Green
2  Lemon               58                  53.0         1.98  Yellow

In [ ]:
# Note swapping the order of the data frames only changes the order the information is displayed.
pd.merge(fruit2,fruit1,on="Name",how="inner")

    Name  Cost ($/lb)   Color  Avg. Weight (g)  Vitamin C (g/100 ml)
0  Lemon         1.98  Yellow               58                  53.0
1  Apple         1.23     Red              186                  27.5
2  Apple         1.67   Green              186                  27.5

``how == "outer"`` displays all information contained in both data frames. Any data that is missing will be set to NaN.

In [ ]:
pd.merge(fruit1,fruit2,on="Name",how="outer")

     Name  Avg. Weight (g)  Vitamin C (g/100 ml)  Cost ($/lb)   Color
0   Apple            186.0                  27.5         1.23     Red
1   Apple            186.0                  27.5         1.67   Green
2  Papaya            275.0                  61.0          NaN     NaN
3   Lemon             58.0                  53.0         1.98  Yellow
4  Orange              NaN                   NaN         1.43  Orange

The other options for how are ``"right"`` and ``"left"``. Try them below and try to figure out what they do.

In [ ]:
pd.merge(fruit1,fruit2,on="Name",how=...)

     Name  Avg. Weight (g)  Vitamin C (g/100 ml)  Cost ($/lb)   Color
0   Apple              186                  27.5         1.23     Red
1   Apple              186                  27.5         1.67   Green
2  Papaya              275                  61.0          NaN     NaN
3   Lemon               58                  53.0         1.98  Yellow

## Activity

In this activity we will analyze the Chicago Census Data available below.

In [ ]:
census = pd.read_csv('data/Chicago_Census_Data.csv')
census.head()

,Community Area Number,COMMUNITY AREA NAME,PERCENT OF HOUSING CROWDED,PERCENT HOUSEHOLDS BELOW POVERTY,PERCENT AGED 16+ UNEMPLOYED,PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA,PERCENT AGED UNDER 18 OR OVER 64,PER CAPITA INCOME,HARDSHIP INDEX
0,1.0,Rogers Park,7.7,23.6,8.7,18.2,27.5,23939,39.0
1,2.0,West Ridge,7.8,17.2,8.8,20.8,38.5,23040,46.0
2,3.0,Uptown,3.8,24.0,8.9,11.8,22.2,35787,20.0
3,4.0,Lincoln Square,3.4,10.9,8.2,13.4,25.5,37524,17.0
4,5.0,North Center,0.3,7.5,5.2,4.5,26.2,57123,6.0

## Exercise 1
Using ``merge`` and the grocery store and AirBnB datasets, build a single data frame that contains the name of the neighborhood, the per capita income, the number of grocery stores, the number of AirBnB's and the Percent of Housing Crowded. Call this dataframe ``neighborhood_df``.

In [ ]:
## YOUR CODE HERE

## Exercise 2

Analyze the grocery data. Call a grocery store "Large" if it is at least 6000 square feet.

a) Add a column to the original dataframe ``grocery_df`` called "Size". Set the value to be "Large" if it is at least 6000 square feet. "Small" if it is less than 6000 square feet, and "Unknown" if the square footage is not known.

b) Use the tools you have including a groupby to get a data frame that counts the number of large grocery stores in each neighborhood.

In [ ]:
# YOUR CODE HERE

## Exercise 3

Then use a merge to add the information about the number of Large Grocery Stores to ``neighborhood_df``. Which options for ``how`` could you use for this merge?

In [ ]:
# YOUR CODE HERE

## Exercise 4

Using what you know identify the two neighborhoods in Chicago, that don't appear in the grocery store dataset.

It should be noted that ``NaN`` values are special. They cannot be checked for with equality like other values. Look into the documentation for the pandas function ``isna`` to help you circumvent this issue.

In [7]:
test_df = pd.DataFrame({"A":[1.0,2.1,np.NaN],"B":[0.0,12,-11]})
test_df.loc[test_df["A"] == np.NaN]

Empty DataFrame
Columns: [A, B]
Index: []