<center> 

# DSSI: Summer 2024
    
## DataFrame Operations
### Merge

#### Authored by: Bill Trok, PhD

<center>
<img src="https://raw.githubusercontent.com/amandakube/Data118LectureImages/main/UChicago_DSI.png" alt="UC-DSI" width="300" height="100">
</center>

In [ ]:
import numpy as np
import pandas as pd

## Focus of this notebook

DataFrame Methods (Operations)

- Merging Data Frames

    - ```pd.merge()```

## Warm-up

Suppose we are interested in the number of grocery stores in each Neighborhood in Chicago. Use the data below and ``groupby`` to count the number of Grocery Stores in each neighborhood of Chicago. The result should be stored in a dataframe called ``grocery_count_df``. The dataframe should have two columns one containing the counts and one containing the "COMMUNITY AREA NAME".

In [ ]:
grocery_df = pd.read_csv('data/groceries.csv')
grocery_df

In [ ]:
# YOUR CODE HERE
grocery_count_df = ...

## Renaming Columns

Often we might want to rename columns of our dataframe to be more descriptive, or to follow a certain format. Remember we can do that with the rename method. Use it to rename the column containing the number of stores to "NUM STORES".

In [ ]:
grocery_count_df = ...

## Recall the  AirBnB Data

In [ ]:
chicago_airbnb_df = pd.read_csv('data/chicago_listings.csv')
chicago_airbnb_df.head(5)

Yesterday, we used this data to count the number of airbnbs in each neighborhood of Chicago.

In [ ]:
chicago_airbnb_df.groupby('neighbourhood')[['id']].count()

## Merge
Frequently, we will have more than one data set that we want to analyze, or we have some data we're interested in that is missing from a data set we do have. For instance, suppose we want to combine the airbnb information with information about grocery stores to get a summary of each neighborhood in Chicago.

To do this we can use the functions merge. When doing this operations, we need to give two columns which contain the same information.

In [ ]:
airbnb_count_df = chicago_airbnb_df.groupby("neighbourhood")[["name"]].count().reset_index()
airbnb_count_df = airbnb_count_df.rename(columns={"name":"num airbnbs"})
airbnb_count_df

In [ ]:
pd.merge(airbnb_count_df,grocery_count_df,left_on="neighbourhood",right_on="COMMUNITY AREA NAME")

You might notice a few things about the resulting dataframe. First, both columns "neighbourhood" and "COMMUNITY AREA NAME" are present in the data frame. Secondly, and more subtly, we actually lost data when doing this merge.

We started with 77 columns in the airbnb data, but end up with a dataset with only 75 columns.

This is in part due to the default behavior of ``pd.merge``. We see different behavior by setting the parameter ``how = "outer"``.

In [ ]:
comb_df = pd.merge(airbnb_count_df,grocery_count_df,left_on="neighbourhood",right_on="COMMUNITY AREA NAME",how="outer")
comb_df

     neighbourhood  num airbnbs COMMUNITY AREA NAME  NUM STORES
0      Albany Park           68         Albany Park        12.0
1   Archer Heights            6      Archer Heights         4.0
2    Armour Square           67       Armour Square         4.0
3          Ashburn           13             Ashburn         3.0
4   Auburn Gresham            6      Auburn Gresham        11.0
..             ...          ...                 ...         ...
72       West Lawn           10           West Lawn         4.0
73    West Pullman            2        West Pullman         5.0
74      West Ridge           69          West Ridge        18.0
75       West Town          725           West Town        14.0
76        Woodlawn           84            Woodlawn         5.0

[77 rows x 4 columns]

## Options for Merge

In fact there are many different options for merge. To get a sense for what's happening let's look at some simple data.

In [ ]:
fruit1 = pd.DataFrame({"Name":["Apple","Papaya","Lemon"],
                       "Avg. Weight (g)":[186,275,58],
                       "Vitamin C (g/100 ml)":[27.5,61,53]})
fruit1

     Name  Avg. Weight (g)  Vitamin C (g/100 ml)
0   Apple              186                  27.5
1  Papaya              275                  61.0
2   Lemon               58                  53.0

In [ ]:
fruit2 = pd.DataFrame({"Name":["Lemon","Apple","Apple","Orange"],
                       "Cost ($/lb)":[1.98,1.23,1.67,1.43],
                       "Color":["Yellow","Red","Green","Orange"]})
fruit2

     Name  Cost ($/lb)   Color
0   Lemon         1.98  Yellow
1   Apple         1.23     Red
2   Apple         1.67   Green
3  Orange         1.43  Orange

Note if two DataFrames have a shared column with the same name, you can just specify the one column name.
The default option for merge is ``how = "inner"``. This combines the data only including rows contained in both dataframes.

In [ ]:
pd.merge(fruit1,fruit2,left_on="Name",right_on="Name")

    Name  Avg. Weight (g)  Vitamin C (g/100 ml)  Cost ($/lb)   Color
0  Apple              186                  27.5         1.23     Red
1  Apple              186                  27.5         1.67   Green
2  Lemon               58                  53.0         1.98  Yellow

In [ ]:
pd.merge(fruit1,fruit2,on="Name",how="inner")

    Name  Avg. Weight (g)  Vitamin C (g/100 ml)  Cost ($/lb)   Color
0  Apple              186                  27.5         1.23     Red
1  Apple              186                  27.5         1.67   Green
2  Lemon               58                  53.0         1.98  Yellow

In [ ]:
# Note swapping the order of the data frames only changes the order the information is displayed.
pd.merge(fruit2,fruit1,on="Name",how="inner")

    Name  Cost ($/lb)   Color  Avg. Weight (g)  Vitamin C (g/100 ml)
0  Lemon         1.98  Yellow               58                  53.0
1  Apple         1.23     Red              186                  27.5
2  Apple         1.67   Green              186                  27.5

``how = "outer"`` displays all information contained in both data frames. Any data that is missing will be set to NaN.

In [ ]:
pd.merge(fruit1,fruit2,on="Name",how="outer")

     Name  Avg. Weight (g)  Vitamin C (g/100 ml)  Cost ($/lb)   Color
0   Apple            186.0                  27.5         1.23     Red
1   Apple            186.0                  27.5         1.67   Green
2  Papaya            275.0                  61.0          NaN     NaN
3   Lemon             58.0                  53.0         1.98  Yellow
4  Orange              NaN                   NaN         1.43  Orange

The other options for how are ``"right"`` and ``"left"``. Try them below and try to figure out what they do.

In [ ]:
pd.merge(fruit1,fruit2,on="Name",how=...)

     Name  Avg. Weight (g)  Vitamin C (g/100 ml)  Cost ($/lb)   Color
0   Apple              186                  27.5         1.23     Red
1   Apple              186                  27.5         1.67   Green
2  Papaya              275                  61.0          NaN     NaN
3   Lemon               58                  53.0         1.98  Yellow

## Activity

In this activity we will analyze the Chicago Census Data available below.

In [ ]:
census = pd.read_csv('data/Chicago_Census_Data.csv')
census.head()

,Community Area Number,COMMUNITY AREA NAME,PERCENT OF HOUSING CROWDED,PERCENT HOUSEHOLDS BELOW POVERTY,PERCENT AGED 16+ UNEMPLOYED,PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA,PERCENT AGED UNDER 18 OR OVER 64,PER CAPITA INCOME,HARDSHIP INDEX
0,1.0,Rogers Park,7.7,23.6,8.7,18.2,27.5,23939,39.0
1,2.0,West Ridge,7.8,17.2,8.8,20.8,38.5,23040,46.0
2,3.0,Uptown,3.8,24.0,8.9,11.8,22.2,35787,20.0
3,4.0,Lincoln Square,3.4,10.9,8.2,13.4,25.5,37524,17.0
4,5.0,North Center,0.3,7.5,5.2,4.5,26.2,57123,6.0

## Exercise 1
Using ``merge`` and the grocery store and AirBnB datasets, build a single data frame that contains the name of the neighborhood, the per capita income, the number of grocery stores, the number of AirBnB's and the Percent of Housing Crowded. Call this dataframe ``neighborhood_df``.

In [ ]:
## YOUR CODE HERE

## Exercise 2

Analyze the grocery data. Call a grocery store "Large" if it is at least 6000 square feet.

a) Add a column to the original dataframe ``grocery_df`` called "Size". Set the value to be "Large" if it is at least 6000 square feet. "Small" if it is less than 6000 square feet, and "Unknown" if the square footage is not known.

b) Use the tools you have including a groupby to get a data frame that counts the number of large grocery stores in each neighborhood.

In [ ]:
# YOUR CODE HERE

## Exercise 3

Then use a merge to add the information about the number of Large Grocery Stores to ``neighborhood_df``. Which options for ``how`` could you use for this merge?

In [ ]:
# YOUR CODE HERE

## Exercise 4

Using what you know identify the two neighborhoods in Chicago, that don't appear in the grocery store dataset.

It should be noted that ``NaN`` values are special. They cannot be checked for with equality like other values. Look into the documentation for the pandas function ``isna`` to help you circumvent this issue.

In [ ]:
test_df = pd.DataFrame({"A":[1.0,2.1,np.NaN],"B":[0.0,12,-11]})
test_df.loc[test_df["A"] == np.NaN]